name: <your project name>
services:
    server:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=<password>
        ports:
            - 1433:1433
        container_name: sql1
        hostname: sql1
        image: mcr.microsoft.com/mssql/server:2022-latest
        command: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sql1 -P P@ssword246. -C
